
export const locationDetails = [
    { city: "New York", state: "New York", country: "USA" },
    { city: "Los Angeles", state: "California", country: "USA" },
    { city: "Chicago", state: "Illinois", country: "USA" },
    { city: "Houston", state: "Texas", country: "USA" },
    { city: "Phoenix", state: "Arizona", country: "USA" },
    { city: "Philadelphia", state: "Pennsylvania", country: "USA" },
    { city: "San Antonio", state: "Texas", country: "USA" },
    { city: "San Diego", state: "California", country: "USA" },
    { city: "Dallas", state: "Texas", country: "USA" },
    { city: "San Jose", state: "California", country: "USA" },
    { city: "Toronto", state: "Ontario", country: "Canada" },
    { city: "Vancouver", state: "British Columbia", country: "Canada" },
    { city: "Montreal", state: "Quebec", country: "Canada" },
    { city: "Mexico City", state: "Mexico City", country: "Mexico" },
    { city: "Guadalajara", state: "Jalisco", country: "Mexico" },
    { city: "Monterrey", state: "Nuevo Leon", country: "Mexico" },
    { city: "London", state: "England", country: "United Kingdom" },
    { city: "Manchester", state: "England", country: "United Kingdom" },
    { city: "Birmingham", state: "England", country: "United Kingdom" },
    { city: "Berlin", state: "Berlin", country: "Germany" },
    { city: "Munich", state: "Bavaria", country: "Germany" },
    { city: "Frankfurt", state: "Hesse", country: "Germany" },
    { city: "Paris", state: "Ile-de-France", country: "France" },
    { city: "Marseille", state: "Provence-Alpes-Cote d'Azur", country: "France" },
    { city: "Lyon", state: "Auvergne-Rhone-Alpes", country: "France" },
    { city: "Rome", state: "Lazio", country: "Italy" },
    { city: "Milan", state: "Lombardy", country: "Italy" },
    { city: "Naples", state: "Campania", country: "Italy" },
    { city: "Madrid", state: "Community of Madrid", country: "Spain" },
    { city: "Barcelona", state: "Catalonia", country: "Spain" },
    { city: "Valencia", state: "Valencian Community", country: "Spain" },
    { city: "Sydney", state: "New South Wales", country: "Australia" },
    { city: "Melbourne", state: "Victoria", country: "Australia" },
    { city: "Brisbane", state: "Queensland", country: "Australia" },
    { city: "Tokyo", state: "Tokyo", country: "Japan" },
    { city: "Osaka", state: "Osaka", country: "Japan" },
    { city: "Nagoya", state: "Aichi", country: "Japan" },
    { city: "Beijing", state: "Beijing", country: "China" },
    { city: "Shanghai", state: "Shanghai", country: "China" },
    { city: "Shenzhen", state: "Guangdong", country: "China" },
    { city: "Moscow", state: "Moscow", country: "Russia" },
    { city: "Saint Petersburg", state: "Saint Petersburg", country: "Russia" },
    { city: "Novosibirsk", state: "Novosibirsk Oblast", country: "Russia" },
    { city: "Rio de Janeiro", state: "Rio de Janeiro", country: "Brazil" },
    { city: "Sao Paulo", state: "Sao Paulo", country: "Brazil" },
    { city: "Brasilia", state: "Federal District", country: "Brazil" },
    { city: "Cape Town", state: "Western Cape", country: "South Africa" },
    { city: "Johannesburg", state: "Gauteng", country: "South Africa" },
    { city: "Durban", state: "KwaZulu-Natal", country: "South Africa" }
];